$ErrorActionPreference = "Stop"
Write-Host "== Generating v2.0 workbench reports ==" -ForegroundColor Cyan

$outDir = "77_Report_Builder"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$out = Join-Path $outDir "workbench_summary_v2_0.md"

$lines = @()
$lines += "# Workbench Summary v2.0"
$lines += ""
$lines += "Generated by v2.0 scripted flow."
$lines += ""
$lines += "## Integrated Components"
$lines += ""
$lines += "- Knowledgebase"
$lines += "- Case engine"
$lines += "- Tollgate rules"
$lines += "- Event graph"
$lines += "- SCD2 state timeline"
$lines += "- Consent and governance cockpit"
$lines += "- Reports"
$lines += "- GitHub Pages"
$lines += "- GitHub Wiki"
$lines += "- Streamlit MVP"
$lines += ""
$lines += "## Live Links"
$lines += ""
$lines += "- Repo: https://github.com/ajaytester007/Purushartha_Family_Continuity_OS"
$lines += "- Wiki: https://github.com/ajaytester007/Purushartha_Family_Continuity_OS/wiki"
$lines += "- Pages: https://ajaytester007.github.io/Purushartha_Family_Continuity_OS/"
$lines += "- Streamlit: https://purusharthafamilycontinuityos-jakkkbzwpuv5pxapptc5up2.streamlit.app/"
$lines += ""
$lines += "## Guardrail"
$lines += ""
$lines += "Use synthetic data publicly. Use real data only in private local mode with consent and purpose controls."

$lines | Set-Content -Encoding UTF8 $out
Write-Host "Generated $out" -ForegroundColor Green
