$ErrorActionPreference = "Stop"

Write-Host "== Generating dashboard outputs ==" -ForegroundColor Cyan

$metricsPath = "20_Dashboard_Data\dashboard_metrics_seed.csv"
$outDir = "29_Dashboard_Outputs"

if (-not (Test-Path $metricsPath)) {
    throw "Missing $metricsPath. Run merge_v1_2.ps1 or merge_v1_3.ps1 first."
}

New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$metrics = Import-Csv $metricsPath

$metrics | Sort-Object metric | Export-Csv "$outDir\metric_status_summary.csv" -NoTypeInformation

$lines = @()
$lines += "# Dashboard Summary"
$lines += ""
$lines += "| Metric | Stage | Value | Threshold | Status |"
$lines += "|---|---|---:|---:|---|"

foreach ($m in $metrics) {
    $lines += "| $($m.metric) | $($m.stage) | $($m.value) | $($m.threshold) | $($m.status) |"
}

$lines += ""
$lines += "Generated by v1.3 dashboard script."
$lines | Set-Content -Encoding UTF8 "$outDir\dashboard_summary.md"

$metrics | Where-Object { $_.metric -eq "Relationship Health" } |
    Export-Csv "$outDir\relationship_health_snapshot.csv" -NoTypeInformation

Write-Host "Dashboard outputs generated in $outDir" -ForegroundColor Green
