$ErrorActionPreference = "Stop"
Write-Host "== Generating family continuity report ==" -ForegroundColor Cyan
$outDir = "53_Report_Exporter"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$out = Join-Path $outDir "family_continuity_summary_v1_8.md"
$lines = @()
$lines += "# Family Continuity Summary v1.8"
$lines += ""
$lines += "Generated by v1.8 scripted flow."
$lines += ""
$lines += "## Live System Links"
$lines += ""
$lines += "- Repo: https://github.com/ajaytester007/Purushartha_Family_Continuity_OS"
$lines += "- Wiki: https://github.com/ajaytester007/Purushartha_Family_Continuity_OS/wiki"
$lines += "- App: https://purusharthafamilycontinuityos-jakkkbzwpuv5pxapptc5up2.streamlit.app/"
$lines += "- Pages: https://ajaytester007.github.io/Purushartha_Family_Continuity_OS/"
$lines += ""
$lines += "## v1.8 Additions"
$lines += ""
$lines += "- Branch-based GitHub Pages deployment"
$lines += "- SCD2 timeline seed"
$lines += "- Event graph preview model"
$lines += "- Expanded report export"
$lines | Set-Content -Encoding UTF8 $out
Write-Host "Generated $out" -ForegroundColor Green
