$ErrorActionPreference = "Stop"
Write-Host "== Generating state transition report v2.6 ==" -ForegroundColor Cyan

$outDir = "108_State_Change_Reports"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$out = Join-Path $outDir "state_transition_report_v2_6.md"

$lines = @()
$lines += "# State Transition Report v2.6"
$lines += ""
$lines += "Generated by v2.6 scripted flow."
$lines += ""
$lines += "## Purpose"
$lines += ""
$lines += "This report documents the controlled SCD2 state-transition model."
$lines += ""
$lines += "## Rule"
$lines += ""
$lines += "Close the current state, create a new current state, and preserve history."

$lines | Set-Content -Encoding UTF8 $out
Write-Host "Generated $out" -ForegroundColor Green
