$ErrorActionPreference = "Stop"

Write-Host "== Merging Purushartha OS v2.1 assets ==" -ForegroundColor Cyan

$Dirs = @(
"82_Reports_Cockpit",
"83_Report_Manifest",
"84_Streamlit_Report_Workbench",
"85_Pages_Report_Cards",
"86_Release_Notes",
"87_Backlog_vNext"
)

foreach ($d in $Dirs) { New-Item -ItemType Directory -Force -Path $d | Out-Null }

@'
# Release Notes - v2.1 Streamlit Workbench Reports Cockpit

## Purpose

v2.1 makes generated workbench reports easier to discover, browse, and publish by adding report manifest, report index, report cockpit documentation, and public report cards.

## Added

- Report manifest CSV.
- Report index Markdown.
- Reports Cockpit model.
- Streamlit report workbench upgrade plan.
- Pages report cards section.
- Wiki publishing update.
- v2.2 backlog for report-builder UI.

## Why This Matters

v2.0 generated reports, but the visibility path was scattered across local Markdown files, GitHub repository folders, and flattened Wiki pages. v2.1 introduces a consistent report catalog.
'@ | Set-Content -Encoding UTF8 "86_Release_Notes\v2.1_Streamlit_Workbench_Reports_Cockpit.md"

@'
# Reports Cockpit

## Purpose

The Reports Cockpit is the front door for generated workbench outputs.

## Report Families

1. Workbench Summary
2. Family Continuity Summary
3. Event Graph Report
4. Relationship Health Report
5. Burden Skew Audit
6. SCD2 State Timeline
7. Consent and Governance Report
8. Case Engine Output
9. Repair Plan Output
10. Retest Schedule

## Cockpit Columns

- Report Name
- Report Type
- Location
- Public or Private
- Generated By
- Last Updated
- Intended Audience
- Guardrail Status

## Operating Principle

Reports should help organize repair, governance, and continuity. They should not become accusations without human review and context.
'@ | Set-Content -Encoding UTF8 "82_Reports_Cockpit\Reports_Cockpit.md"

@'
# Report Manifest Model

The report manifest provides a machine-readable catalog of generated reports.

## Fields

- report_id
- report_name
- report_type
- local_path
- wiki_page_hint
- public_private_mode
- generated_by
- audience
- guardrail_status

## Use

The Streamlit workbench can read the manifest and show report cards.
'@ | Set-Content -Encoding UTF8 "83_Report_Manifest\Report_Manifest_Model.md"

@'
# Streamlit Report Workbench

## v2.1 Direction

Add a Reports tab to the Streamlit app that reads the report manifest and displays:

- Report cards
- Markdown preview
- Download buttons
- Public/private mode
- Guardrail status
- Last generated status

## v2.2 Target

Build the actual interactive report-builder UI.
'@ | Set-Content -Encoding UTF8 "84_Streamlit_Report_Workbench\Streamlit_Report_Workbench.md"

@'
# Pages Report Cards

## Purpose

GitHub Pages should show public report cards that point users to the repository and Wiki pages.

## Public Reports

Only synthetic or generic reports should be shown publicly.

## Private Reports

Private reports should remain local unless explicitly sanitized.
'@ | Set-Content -Encoding UTF8 "85_Pages_Report_Cards\Pages_Report_Cards.md"

@'
# v2.2 Backlog

## Theme

Interactive Report Builder UI

## Candidate Enhancements

- Streamlit report manifest reader.
- Report card grid.
- Markdown report preview.
- Download buttons.
- Generate selected report.
- Public/private mode switch.
- Consent and guardrail badge.
- Report freshness indicator.
- Report-to-Wiki publisher.
'@ | Set-Content -Encoding UTF8 "87_Backlog_vNext\v2.2_Backlog.md"

Write-Host "v2.1 assets merged successfully." -ForegroundColor Green
