from pathlib import Path

app=Path("51_Streamlit_MVP/app.py")
text=app.read_text(encoding="utf-8-sig").replace("\ufeff","")
marker="# === V4.4 REAL ANONYMOUS PILOT LAB ==="
if marker in text:
    print("v4.4 patch already present")
    raise SystemExit(0)

lines=[
"# === V4.4 REAL ANONYMOUS PILOT LAB ===",
"def decision_v44(score, gap, drama):",
"    if drama >= 75: return 'Pause: drama load is too high; de-escalate before milestone movement.'",
"    if gap >= 35: return 'Incubate: perspectives are far apart; run a clarity and repair quest.'",
"    if score >= 85: return 'Continue: strong readiness with normal monitoring.'",
"    if score >= 70: return 'Continue with coaching: promising but needs targeted quests.'",
"    if score >= 55: return 'Pause and retest: gaps must visibly improve.'",
"    if score >= 40: return 'High caution: consider mediated support and delayed milestone.'",
"    return 'Exit review: preserve learning and avoid forcing the bond.'",
"",
"st.markdown('---')",
"st.header('🧪 v4.4 Real Anonymous Pilot Lab')",
"st.caption('Test anonymous relationship cases with multi-rater scoring, perspective pivots, decision maze, and coaching retest plans.')",
"st.warning('Use aliases only. Do not enter real identifying details in the public app.')",
"",
"pilot_v44=st.text_input('Anonymous Pilot Code', value='LOTUS-001', key='pilot_v44')",
"stage_v44=st.selectbox('Pilot Stage', ['Dating','Engaged','Makeover','Recovery','Wedding Launch Gate','Household Takeoff'], key='stage_v44')",
"episode_v44=st.text_area('Moment-of-Truth Episode', placeholder='Describe the episode with aliases only...', key='episode_v44')",
"",
"st.subheader('👥 Multi-Rater Scores')",
"roles_v44=['Partner-A','Partner-B','Parent-A','Parent-B','Sibling/Friend','Seer/Mentor','Support System']",
"role_scores_v44=[]",
"for i,role in enumerate(roles_v44):",
"    role_scores_v44.append(st.slider(role+' rating',0,100,70,key=f'role_score_v44_{i}'))",
"avg_role_v44=round(sum(role_scores_v44)/len(role_scores_v44),1)",
"gap_v44=max(role_scores_v44)-min(role_scores_v44)",
"",
"st.subheader('🧭 Perspective Pivots')",
"pivot_v44=st.multiselect('Which views should be considered?', ['My intention','Partner experience','Parent/family influence','Child/future-child lens','Pets/care ecosystem','Friends/colleagues/support system','Seer lens','Dharma/Artha/Kama/Moksha'], default=['My intention','Partner experience','Parent/family influence','Seer lens'], key='pivot_v44')",
"facts_v44=st.text_area('Facts', key='facts_v44', placeholder='What is objectively known?')",
"feelings_v44=st.text_area('Feelings', key='feelings_v44', placeholder='What emotions surfaced?')",
"assumptions_v44=st.text_area('Assumptions', key='assumptions_v44', placeholder='What might be assumed but not proven?')",
"",
"st.subheader('🌪️ Emotional Drama Sanity')",
"escalation_v44=st.slider('Escalation load',0,100,40,key='escalation_v44')",
"triangulation_v44=st.slider('Triangulation / third-party noise',0,100,35,key='triangulation_v44')",
"repair_v44=st.slider('Visible repair behavior',0,100,65,key='repair_v44')",
"drama_v44=round(escalation_v44*.45+triangulation_v44*.35+(100-repair_v44)*.20,1)",
"",
"st.subheader('🕉️ Purushartha Decision Map')",
"p1,p2,p3,p4=st.columns(4)",
"with p1: dharma_v44=st.slider('Dharma',0,100,75,key='dharma_v44')",
"with p2: artha_v44=st.slider('Artha',0,100,70,key='artha_v44')",
"with p3: kama_v44=st.slider('Kama',0,100,75,key='kama_v44')",
"with p4: moksha_v44=st.slider('Moksha',0,100,70,key='moksha_v44')",
"purushartha_v44=round((dharma_v44*.30+artha_v44*.25+kama_v44*.20+moksha_v44*.25),1)",
"decision_score_v44=round(avg_role_v44*.35+purushartha_v44*.40+(100-drama_v44)*.25,1)",
"",
"st.subheader('📊 Pilot Decision Dashboard')",
"a,b,c,d=st.columns(4)",
"a.metric('Multi-Rater Avg', f'{avg_role_v44}/100')",
"b.metric('Perspective Gap', gap_v44)",
"c.metric('Drama Load', f'{drama_v44}/100')",
"d.metric('Decision Score', f'{decision_score_v44}/100')",
"recommendation_v44=decision_v44(decision_score_v44, gap_v44, drama_v44)",
"st.info(recommendation_v44)",
"",
"st.subheader('🌀 First Decision Maze')",
"maze_v44=[",
"('My Intention','What was I trying to do?'),",
"('Partner Experience','How might my partner have experienced it?'),",
"('Family Influence','What family expectation entered?'),",
"('Practical Constraints','What budget, distance, time, health, or logistics mattered?'),",
"('Emotional Activation','What old wound or fear may have been activated?'),",
"('Facts vs Assumptions','What is known and what is assumed?'),",
"('Purushartha View','What do Dharma, Artha, Kama, and Moksha reveal?'),",
"('Repair Choices','What repair choices are available?'),",
"('Consequence Preview','What happens if we continue, pause, incubate, or exit?'),",
"('Next Tollgate','What must be retested before the next milestone?')",
"]",
"for idx,(node,q) in enumerate(maze_v44):",
"    with st.expander(f'{idx+1}. {node}', expanded=(idx<2)):",
"        st.write(q)",
"        st.text_area('Maze note', key=f'maze_note_v44_{idx}', placeholder='Optional anonymous reflection...')",
"",
"st.subheader('🎯 Coaching Quest + Retest')",
"if gap_v44>=35:",
"    quest_v44='Clarity Bridge Quest: each side writes intention, impact, and one needed repair before discussing again.'",
"elif drama_v44>=60:",
"    quest_v44='Drama Cooling Quest: pause, separate facts from assumptions, and retest after 48 hours.'",
"elif artha_v44<60:",
"    quest_v44='Artha Reality Quest: create one practical budget/logistics substitution plan.'",
"elif kama_v44<60:",
"    quest_v44='Kama Renewal Quest: create one low-cost joy or affection ritual.'",
"else:",
"    quest_v44='Momentum Quest: preserve one strength and complete one small promise.'",
"st.success(quest_v44)",
"",
"if st.button('Generate v4.4 Anonymous Pilot Report', key='generate_report_v44'):",
"    report=f'''# v4.4 Anonymous Pilot Report",
"",
"## Pilot Code",
"{pilot_v44}",
"",
"## Stage",
"{stage_v44}",
"",
"## Recommendation",
"{recommendation_v44}",
"",
"## Scores",
"- Multi-Rater Average: {avg_role_v44}/100",
"- Perspective Gap: {gap_v44}",
"- Drama Load: {drama_v44}/100",
"- Purushartha Score: {purushartha_v44}/100",
"- Decision Score: {decision_score_v44}/100",
"",
"## Perspective Pivots",
"{', '.join(pivot_v44)}",
"",
"## Facts",
"{facts_v44 or 'Not supplied'}",
"",
"## Feelings",
"{feelings_v44 or 'Not supplied'}",
"",
"## Assumptions",
"{assumptions_v44 or 'Not supplied'}",
"",
"## Coaching Quest",
"{quest_v44}",
"",
"## Retest Plan",
"Retest the lowest-scoring or highest-gap area after 7-14 days of visible behavior change.",
"",
"## Safety Rule",
"Safety and dignity override relationship optimization.",
"'''",
"    st.markdown(report)",
"    st.download_button('Download v4.4 Pilot Report', report, 'v4_4_anonymous_pilot_report.md', 'text/markdown', key='download_report_v44')",
"# === END V4.4 REAL ANONYMOUS PILOT LAB ===",
]
app.write_text(text+'\n\n'+'\n'.join(lines)+'\n', encoding='utf-8')
print('v4.4 Streamlit patch complete.')
