from pathlib import Path
app=Path("51_Streamlit_MVP/app.py")
text=app.read_text(encoding="utf-8-sig").replace("\ufeff","")
marker="# === V4.3 ANONYMOUS PILOT DECISIONING ==="
if marker in text:
    print("v4.3 patch already present")
    raise SystemExit(0)

lines=[
"# === V4.3 ANONYMOUS PILOT DECISIONING ===",
"def decision_band_v43(score):",
"    if score >= 85: return 'Continue toward launch — strong dharmic viability.'",
"    if score >= 70: return 'Continue with incubation — promising but needs hand-holding.'",
"    if score >= 55: return 'Pause and retest — gaps must be coached before next milestone.'",
"    if score >= 40: return 'High caution — significant drama/logistics/family risks.'",
"    return 'Exit review — preserve maturity gained and consider a new game later.'",
"",
"def drama_band_v43(score):",
"    if score <= 25: return 'Low drama load — emotions are manageable.'",
"    if score <= 50: return 'Moderate drama load — use boundaries and reality checks.'",
"    if score <= 75: return 'High drama load — pause, de-escalate, and retest.'",
"    return 'Critical drama load — safety, dignity, and trauma-loop review needed.'",
"",
"st.markdown('---')",
"st.header('🧭 v4.3 Anonymous Pilot Decisioning Lab')",
"st.caption('Use aliases only. Evaluate real-life readiness through Purushartha quadrants, seer lenses, drama sanity checks, and wedding union staging.')",
"st.warning('Do not enter real names, phone numbers, addresses, health identifiers, or private third-party details in the public app.')",
"",
"pilot_id_v43=st.text_input('Anonymous Pilot ID', value='LOTUS-001', key='pilot_id_v43')",
"stage_v43=st.selectbox('Wedding Union Stage', ['Seed Chemistry','Early Alignment','Family Awareness','Role Play Incubation','Repair Retest','Budget Logistics Gate','Wedding Launch Gate','Household Takeoff'], key='stage_v43')",
"seer_lens_v43=st.multiselect('Seer / Trusted Lens Applied', ['Dharma Lens','Artha Lens','Kama Lens','Moksha Lens','Family Ecosystem Lens','Modern Life Lens','Recovery Lens','Wedding Launch Lens'], default=['Dharma Lens','Family Ecosystem Lens'], key='seer_lens_v43')",
"",
"st.subheader('🕉️ Purushartha Quadrant Risk Map')",
"c1,c2,c3,c4=st.columns(4)",
"with c1: dharma_v43=st.slider('Dharma',0,100,75,key='dharma_v43')",
"with c2: artha_v43=st.slider('Artha',0,100,70,key='artha_v43')",
"with c3: kama_v43=st.slider('Kama',0,100,75,key='kama_v43')",
"with c4: moksha_v43=st.slider('Moksha',0,100,70,key='moksha_v43')",
"",
"st.subheader('🌪️ Emotional Drama Sanity Check')",
"drama_spike_v43=st.slider('Escalation / emotional drama spike',0,100,35,key='drama_spike_v43')",
"trauma_loop_v43=st.slider('Trauma-bond caution / repeated hurt-repair loop',0,100,30,key='trauma_loop_v43')",
"reality_check_v43=st.slider('Reality check quality: facts separated from assumptions',0,100,70,key='reality_check_v43')",
"repair_visible_v43=st.slider('Visible repair attempt',0,100,65,key='repair_visible_v43')",
"",
"st.subheader('👨‍👩‍👧 Family Ecosystem + Trusted Circle')",
"family_support_v43=st.slider('Family support without control',0,100,70,key='family_support_v43')",
"circle_stability_v43=st.slider('Trusted circle stability',0,100,65,key='circle_stability_v43')",
"budget_logistics_v43=st.slider('Budget, distance, cost, and logistics feasibility',0,100,65,key='budget_logistics_v43')",
"roleplay_maturity_v43=st.slider('Role-play / moment-of-truth maturity',0,100,70,key='roleplay_maturity_v43')",
"",
"purushartha_score_v43=round((dharma_v43*.30+artha_v43*.25+kama_v43*.20+moksha_v43*.25),1)",
"drama_load_v43=round((drama_spike_v43*.35+trauma_loop_v43*.35+(100-reality_check_v43)*.15+(100-repair_visible_v43)*.15),1)",
"ecosystem_score_v43=round((family_support_v43*.30+circle_stability_v43*.20+budget_logistics_v43*.25+roleplay_maturity_v43*.25),1)",
"decision_score_v43=round((purushartha_score_v43*.45+ecosystem_score_v43*.35+(100-drama_load_v43)*.20),1)",
"",
"st.subheader('📊 Decisioning Dashboard')",
"d1,d2,d3,d4=st.columns(4)",
"d1.metric('Purushartha Fit', f'{purushartha_score_v43}/100')",
"d2.metric('Drama Load', f'{drama_load_v43}/100')",
"d3.metric('Ecosystem Support', f'{ecosystem_score_v43}/100')",
"d4.metric('Decision Readiness', f'{decision_score_v43}/100')",
"st.info(decision_band_v43(decision_score_v43))",
"st.warning(drama_band_v43(drama_load_v43))",
"",
"st.subheader('Moment of Truth Log')",
"episode_v43=st.text_area('Anonymous episode / role-play notes', placeholder='Describe the moment of truth with aliases only...', key='episode_v43')",
"coach_gap_v43=st.text_area('Coaching gap noticed', placeholder='What needs to mature before the next stage?', key='coach_gap_v43')",
"",
"if st.button('Generate Anonymous Decision Report', key='generate_decision_report_v43'):",
"    report=f'''# Anonymous Pilot Decision Report",
"",
"## Pilot ID",
"{pilot_id_v43}",
"",
"## Stage",
"{stage_v43}",
"",
"## Seer Lenses",
"{', '.join(seer_lens_v43)}",
"",
"## Scores",
"- Purushartha Fit: {purushartha_score_v43}/100",
"- Emotional Drama Load: {drama_load_v43}/100",
"- Ecosystem Support: {ecosystem_score_v43}/100",
"- Decision Readiness: {decision_score_v43}/100",
"",
"## Recommendation",
"{decision_band_v43(decision_score_v43)}",
"",
"## Drama Sanity Check",
"{drama_band_v43(drama_load_v43)}",
"",
"## Moment of Truth",
"{episode_v43 or 'Not supplied'}",
"",
"## Coaching Gap",
"{coach_gap_v43 or 'Not supplied'}",
"",
"## Retest Plan",
"Retest the lowest scoring dimension after 7-14 days of visible behavior change.",
"",
"## Exit Rule",
"If safety, dignity, repeated non-repair, coercion, or no-hope signals dominate, prepare a dignified exit report that preserves maturity gained.",
"'''",
"    st.markdown(report)",
"    st.download_button('Download Anonymous Decision Report', report, 'anonymous_decision_report.md', 'text/markdown', key='download_decision_report_v43')",
"# === END V4.3 ANONYMOUS PILOT DECISIONING ===",
]
app.write_text(text+'\n\n'+'\n'.join(lines)+'\n', encoding='utf-8')
print('v4.3 Streamlit patch complete.')
